name: Node.js CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint